clients = []
# Beijing Timezone
consumer_duration_in_seconds = 5
default_timezone_offset_in_seconds = 28800
env = "development"
invite_only = false
max_accounts = 1000
max_page_size = 50
page_size = 30
use_fixed_code = false
[image_file_server]
access_key_id = ""
access_key_secret = ""
bucket_url = ""
region = "ap-shanghai"
[avatar_file_server]
access_key_id = ""
access_key_secret = ""
bucket_url = ""
region = "ap-shanghai"
[post]
default_background_colors = [
  "#00b894",
  "#4bcffa",
  "#74b9ff",
  "#a29bfe",
  "#2d3436",
  "#b8e994",
  "#ff7675",
  "#fd79a8",
  "#FBDF4C",
  "#FFB3A7",
  "#89729E",
  "#F8CA47",
  "#3A6CAF",
]
default_listed_posts_duration_in_days = 30
max_post_content_count = 500
max_time_cursor_change_count = 2
min_duration_between_posts_in_minutes = 180
min_post_content_count = 6
vip_min_duration_between_posts_in_minutes = 30
[auth]
access_token_expires_in_minutes = 1440
phone_code_verification_duration_in_seconds = 60
phone_code_verification_expires_in_minutes = 10
public_key = ""
refresh_token_expires_in_days = 180
secret_key = ""
signature_client_date_expires_in_minutes = 5
[i18n]
fallback_language = "zh-Hans"
[server]
socket_address = "0.0.0.0:3000"
url = "http://localhost:4000"

[log]
level = "info"

[db]

max_connections = 10
url = ""

[kv]

url = "redis://127.0.0.1:6379"
[account]
max_bio_length = 100
max_birthday_change_count = 1
max_gender_change_count = 1
max_name_length = 20
max_profile_images = 6
min_age = 18
min_bio_length = 1
min_name_length = 1
signup_queue_path = "data/signup_queue.qf"

[im]
api_key = ""
api_url = "https://im-api.scuinfo.com"
domain = "xmpp.scuinfo.com"
team_account_id = 0
welcome_message = "欢迎来到和我交朋友，有任何问题，请联系小助手"
[notification]
default_listed_notifications_duration_in_days = 30
ifttt_event = "notice"
ifttt_key = ""
[admin]
# default_account_id = 0
