clients = []
# Beijing Timezone
default_timezone_offset_in_seconds = 28800
env = "development"
invite_only = false
max_accounts = 1000
max_page_size = 50
page_size = 30
use_fixed_code = false
[profile_image_file_server]
access_key_id = ""
access_key_secret = ""
bucket_url = ""
region = "ap-shanghai"
[post]
default_background_colors = [
  "#264653",
  "#2a9d8f",
  "#6b705c",
  "#457b9d",
  "#b5179e",
  "#fca311",
  "#ef476f",
  "#90be6d",
]
default_listed_posts_duration_in_days = 30
min_post_content_count = 6
[auth]
access_token_expires_in_minutes = 1440
phone_code_verification_duration_in_seconds = 60
phone_code_verification_expires_in_minutes = 10
public_key = ""
refresh_token_expires_in_days = 180
secret_key = ""
signature_client_date_expires_in_minutes = 5
[i18n]
fallback_language = "zh-Hans"
[server]
socket_address = "0.0.0.0:3000"
url = "http://localhost:4000"

[log]
level = "info"

[db]

max_connections = 10
url = ""

[kv]

url = "redis://127.0.0.1:6379"
[account]
max_profile_images = 9
min_age = 18

[im]
admin_account_id = 0
api_key = ""
api_url = "https://im-api.scuinfo.com"
domain = "xmpp.scuinfo.com"

[notification]
default_listed_notifications_duration_in_days = 30

[admin]
# default_account_id = 0
