clients = []
env = "development"

[auth]
access_token_expires_in_days = 14
phone_code_verification_expires_in_minutes = 10
public_key = ""
refresh_token_expires_in_days = 180
secret_key = ""
signature_client_date_expires_in_minutes = 5
[i18n]
fallback_language = "zh-Hans"
language = "auto"
[server]
host = "127.0.0.1"
port = "3000"
url = "http://localhost:4000"

[log]
level = "info"

[db]

max_connections = 10
url = ""

[kv]

url = "redis://127.0.0.1:6379"
